package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private int role;
     private String securityquestion;
     private String securityquestionans;
     private Set<Character> characters = new HashSet<Character>(0);

    public Account() {
    }

	
    public Account(String username, String password, String email, int role, String securityquestion, String securityquestionans) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
        this.securityquestion = securityquestion;
        this.securityquestionans = securityquestionans;
    }
    public Account(String username, String password, String email, int role, String securityquestion, String securityquestionans, Set<Character> characters) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.role = role;
       this.securityquestion = securityquestion;
       this.securityquestionans = securityquestionans;
       this.characters = characters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    public String getSecurityquestion() {
        return this.securityquestion;
    }
    
    public void setSecurityquestion(String securityquestion) {
        this.securityquestion = securityquestion;
    }
    public String getSecurityquestionans() {
        return this.securityquestionans;
    }
    
    public void setSecurityquestionans(String securityquestionans) {
        this.securityquestionans = securityquestionans;
    }
    public Set<Character> getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Set<Character> characters) {
        this.characters = characters;
    }




}


