package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private AreaId id;
     private Zone zone;
     private String comment;

    public Area() {
    }

	
    public Area(AreaId id, Zone zone) {
        this.id = id;
        this.zone = zone;
    }
    public Area(AreaId id, Zone zone, String comment) {
       this.id = id;
       this.zone = zone;
       this.comment = comment;
    }
   
    public AreaId getId() {
        return this.id;
    }
    
    public void setId(AreaId id) {
        this.id = id;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


