package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * AreaId generated by hbm2java
 */
public class AreaId  implements java.io.Serializable {


     private String name;
     private String zoneName;

    public AreaId() {
    }

    public AreaId(String name, String zoneName) {
       this.name = name;
       this.zoneName = zoneName;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AreaId) ) return false;
		 AreaId castOther = ( AreaId ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getZoneName()==castOther.getZoneName()) || ( this.getZoneName()!=null && castOther.getZoneName()!=null && this.getZoneName().equals(castOther.getZoneName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getZoneName() == null ? 0 : this.getZoneName().hashCode() );
         return result;
   }   


}


