package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * CharacterStatistics generated by hbm2java
 */
public class CharacterStatistics  implements java.io.Serializable {


     private Integer charId;
     private Integer playtime;
     private Integer moneyspent;
     private Integer deaths;
     private Integer slainmobs;
     private Integer duelswon;
     private Integer duelslost;
     private Integer areasdiscov;
     private String comment;

    public CharacterStatistics() {
    }

    public CharacterStatistics(Integer playtime, Integer moneyspent, Integer deaths, Integer slainmobs, Integer duelswon, Integer duelslost, Integer areasdiscov, String comment) {
       this.playtime = playtime;
       this.moneyspent = moneyspent;
       this.deaths = deaths;
       this.slainmobs = slainmobs;
       this.duelswon = duelswon;
       this.duelslost = duelslost;
       this.areasdiscov = areasdiscov;
       this.comment = comment;
    }
   
    public Integer getCharId() {
        return this.charId;
    }
    
    public void setCharId(Integer charId) {
        this.charId = charId;
    }
    public Integer getPlaytime() {
        return this.playtime;
    }
    
    public void setPlaytime(Integer playtime) {
        this.playtime = playtime;
    }
    public Integer getMoneyspent() {
        return this.moneyspent;
    }
    
    public void setMoneyspent(Integer moneyspent) {
        this.moneyspent = moneyspent;
    }
    public Integer getDeaths() {
        return this.deaths;
    }
    
    public void setDeaths(Integer deaths) {
        this.deaths = deaths;
    }
    public Integer getSlainmobs() {
        return this.slainmobs;
    }
    
    public void setSlainmobs(Integer slainmobs) {
        this.slainmobs = slainmobs;
    }
    public Integer getDuelswon() {
        return this.duelswon;
    }
    
    public void setDuelswon(Integer duelswon) {
        this.duelswon = duelswon;
    }
    public Integer getDuelslost() {
        return this.duelslost;
    }
    
    public void setDuelslost(Integer duelslost) {
        this.duelslost = duelslost;
    }
    public Integer getAreasdiscov() {
        return this.areasdiscov;
    }
    
    public void setAreasdiscov(Integer areasdiscov) {
        this.areasdiscov = areasdiscov;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


