package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * CharacterHasSpells generated by hbm2java
 */
public class CharacterHasSpells  implements java.io.Serializable {


     private int id;
     private Integer spellId;
     private Integer charId;

    public CharacterHasSpells() {
    }

	
    public CharacterHasSpells(int id) {
        this.id = id;
    }
    public CharacterHasSpells(int id, Integer spellId, Integer charId) {
       this.id = id;
       this.spellId = spellId;
       this.charId = charId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getSpellId() {
        return this.spellId;
    }
    
    public void setSpellId(Integer spellId) {
        this.spellId = spellId;
    }
    public Integer getCharId() {
        return this.charId;
    }
    
    public void setCharId(Integer charId) {
        this.charId = charId;
    }




}


