package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * CharacterHasEquipment generated by hbm2java
 */
public class CharacterHasEquipment  implements java.io.Serializable {


     private int id;
     private Integer charId;
     private Integer equipId;
     private Integer amount;

    public CharacterHasEquipment() {
    }

	
    public CharacterHasEquipment(int id) {
        this.id = id;
    }
    public CharacterHasEquipment(int id, Integer charId, Integer equipId, Integer amount) {
       this.id = id;
       this.charId = charId;
       this.equipId = equipId;
       this.amount = amount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getCharId() {
        return this.charId;
    }
    
    public void setCharId(Integer charId) {
        this.charId = charId;
    }
    public Integer getEquipId() {
        return this.equipId;
    }
    
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }




}


