package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * CharacterHasItems generated by hbm2java
 */
public class CharacterHasItems  implements java.io.Serializable {


     private int id;
     private Integer charId;
     private Integer itemId;
     private Integer amount;
     private String characterHasItemscol;

    public CharacterHasItems() {
    }

	
    public CharacterHasItems(int id) {
        this.id = id;
    }
    public CharacterHasItems(int id, Integer charId, Integer itemId, Integer amount, String characterHasItemscol) {
       this.id = id;
       this.charId = charId;
       this.itemId = itemId;
       this.amount = amount;
       this.characterHasItemscol = characterHasItemscol;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getCharId() {
        return this.charId;
    }
    
    public void setCharId(Integer charId) {
        this.charId = charId;
    }
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public String getCharacterHasItemscol() {
        return this.characterHasItemscol;
    }
    
    public void setCharacterHasItemscol(String characterHasItemscol) {
        this.characterHasItemscol = characterHasItemscol;
    }




}


