package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * Equipment generated by hbm2java
 */
public class Equipment  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer type;
     private String sellvalue;
     private String flavourtext;
     private String comment;
     private Integer affectedAttriId;
     private Integer affectedAttriSecondId;
     private Integer affFirstValue;
     private Integer affSecondValue;

    public Equipment() {
    }

    public Equipment(String name, Integer type, String sellvalue, String flavourtext, String comment, Integer affectedAttriId, Integer affectedAttriSecondId, Integer affFirstValue, Integer affSecondValue) {
       this.name = name;
       this.type = type;
       this.sellvalue = sellvalue;
       this.flavourtext = flavourtext;
       this.comment = comment;
       this.affectedAttriId = affectedAttriId;
       this.affectedAttriSecondId = affectedAttriSecondId;
       this.affFirstValue = affFirstValue;
       this.affSecondValue = affSecondValue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getSellvalue() {
        return this.sellvalue;
    }
    
    public void setSellvalue(String sellvalue) {
        this.sellvalue = sellvalue;
    }
    public String getFlavourtext() {
        return this.flavourtext;
    }
    
    public void setFlavourtext(String flavourtext) {
        this.flavourtext = flavourtext;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getAffectedAttriId() {
        return this.affectedAttriId;
    }
    
    public void setAffectedAttriId(Integer affectedAttriId) {
        this.affectedAttriId = affectedAttriId;
    }
    public Integer getAffectedAttriSecondId() {
        return this.affectedAttriSecondId;
    }
    
    public void setAffectedAttriSecondId(Integer affectedAttriSecondId) {
        this.affectedAttriSecondId = affectedAttriSecondId;
    }
    public Integer getAffFirstValue() {
        return this.affFirstValue;
    }
    
    public void setAffFirstValue(Integer affFirstValue) {
        this.affFirstValue = affFirstValue;
    }
    public Integer getAffSecondValue() {
        return this.affSecondValue;
    }
    
    public void setAffSecondValue(Integer affSecondValue) {
        this.affSecondValue = affSecondValue;
    }




}


