package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * Levels generated by hbm2java
 */
public class Levels  implements java.io.Serializable {


     private String level;
     private Integer expneeded;
     private String comment;

    public Levels() {
    }

	
    public Levels(String level) {
        this.level = level;
    }
    public Levels(String level, Integer expneeded, String comment) {
       this.level = level;
       this.expneeded = expneeded;
       this.comment = comment;
    }
   
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public Integer getExpneeded() {
        return this.expneeded;
    }
    
    public void setExpneeded(Integer expneeded) {
        this.expneeded = expneeded;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


