package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1



/**
 * Spells generated by hbm2java
 */
public class Spells  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer manacost;
     private String type;
     private String element;
     private Integer damage;
     private String comment;
     private String specproc;
     private String statuseffect;

    public Spells() {
    }

	
    public Spells(String name) {
        this.name = name;
    }
    public Spells(String name, Integer manacost, String type, String element, Integer damage, String comment, String specproc, String statuseffect) {
       this.name = name;
       this.manacost = manacost;
       this.type = type;
       this.element = element;
       this.damage = damage;
       this.comment = comment;
       this.specproc = specproc;
       this.statuseffect = statuseffect;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getManacost() {
        return this.manacost;
    }
    
    public void setManacost(Integer manacost) {
        this.manacost = manacost;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getElement() {
        return this.element;
    }
    
    public void setElement(String element) {
        this.element = element;
    }
    public Integer getDamage() {
        return this.damage;
    }
    
    public void setDamage(Integer damage) {
        this.damage = damage;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getSpecproc() {
        return this.specproc;
    }
    
    public void setSpecproc(String specproc) {
        this.specproc = specproc;
    }
    public String getStatuseffect() {
        return this.statuseffect;
    }
    
    public void setStatuseffect(String statuseffect) {
        this.statuseffect = statuseffect;
    }




}


