package jsrpg;
// Generated Jan 8, 2017 5:32:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private String name;
     private String comment;
     private Set<Area> areas = new HashSet<Area>(0);

    public Zone() {
    }

	
    public Zone(String name) {
        this.name = name;
    }
    public Zone(String name, String comment, Set<Area> areas) {
       this.name = name;
       this.comment = comment;
       this.areas = areas;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }




}


